workspace 'GarbageClassificationUIKit.xcworkspace'

platform :ios, '8.0'
inhibit_all_warnings!
use_frameworks!

def garbageClassificationUIKit_pods
  pod 'AWGarbageClassificationAPIKit'
end

target 'GarbageClassificationUIKit' do
  garbageClassificationUIKit_pods
end

target 'GarbageClassificationUIKitDemo' do
  garbageClassificationUIKit_pods
end
